#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CSV browser for candidate probolisms.

Required packages:
    pip install pandas pillow requests astropy

The program reads CSV files generated by the separate probolism-search program,
downloads preview images from CDS/Aladin HiPS2FITS, saves them in a local cache,
and lets the user browse records with keyboard arrows or the mouse wheel.
"""

from __future__ import annotations

import hashlib
import json
import math
import queue
import re
import shutil
import sys
import threading
import time
import traceback
import webbrowser
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlencode

# -----------------------------------------------------------------------------
# Dependency check
# -----------------------------------------------------------------------------
# The package installed from pip is called "Pillow", but in code it is imported
# as "PIL". This block gives a readable Windows message instead of a raw
# ModuleNotFoundError.


def _dependency_error(missing_packages: List[str], details: str = "") -> None:
    unique: List[str] = []
    for pkg in missing_packages:
        if pkg not in unique:
            unique.append(pkg)
    install_cmd = f'"{sys.executable}" -m pip install --upgrade ' + " ".join(unique)
    msg = (
        "Required Python packages are missing:\n\n"
        + "\n".join(f"  • {pkg}" for pkg in unique)
        + "\n\nInstall them with this command in PowerShell / Terminal:\n\n"
        + install_cmd
    )
    if details:
        msg += "\n\nTechnical details:\n" + details
    try:
        import tkinter as _tk
        from tkinter import messagebox as _messagebox
        _root = _tk.Tk()
        _root.withdraw()
        _messagebox.showerror("Missing Python packages", msg)
        _root.destroy()
    except Exception:
        pass
    print(msg, file=sys.stderr)
    raise SystemExit(1)


_missing: List[str] = []
_import_details: List[str] = []

try:
    import pandas as pd
except Exception as exc:  # pragma: no cover
    _missing.append("pandas")
    _import_details.append(f"pandas: {exc}")

try:
    import requests
except Exception as exc:  # pragma: no cover
    _missing.append("requests")
    _import_details.append(f"requests: {exc}")

try:
    from PIL import Image, ImageTk, ImageDraw, ImageFont
except Exception as exc:  # pragma: no cover
    _missing.append("pillow")
    _import_details.append(f"Pillow/PIL: {exc}")

try:
    import astropy.units as u
    from astropy.coordinates import SkyCoord, get_constellation
except Exception as exc:  # pragma: no cover
    _missing.append("astropy")
    _import_details.append(f"astropy: {exc}")

if _missing:
    _dependency_error(_missing, "\n".join(_import_details))

import tkinter as tk
from tkinter import filedialog, messagebox, ttk


APP_TITLE = "Probolisms browser by piotrs v1_11"
HIPS2FITS_PRIMARY = "https://alasky.cds.unistra.fr/hips-image-services/hips2fits"
HIPS2FITS_MIRROR = "https://alaskybis.cds.unistra.fr/hips-image-services/hips2fits"
DEFAULT_CACHE_DIR = "probolism_image_cache"
DEFAULT_IMAGE_SIZE_PX = 900
SUPPORTED_FOV_BASE = [0.3, 0.5, 0.7, 1.0, 2.0, 4.0]
DISPLAY_MARGIN_DEG = 0.1
AUTO_GALAXY_MARGIN_DEG = 0.05
REQUEST_TIMEOUT_SEC = 60
BULK_DOWNLOAD_RETRIES = 4
BULK_RETRY_DELAY_SEC = 1.5
CTRL_MASK = 0x0004

SURVEY_CHOICES = [
    "CDS/P/DSS2/color",          # whole sky, good default optical preview
    "CDS/P/DSS2/red",
    "CDS/P/2MASS/color",
    "CDS/P/AllWISE/color",
    "CDS/P/PanSTARRS/DR1/color-z-zg-g",
    "CDS/P/SDSS9/color",
]

REQUIRED_OR_USEFUL_COLUMNS = [
    "center_RA", "center_DEC", "center_RA_current", "center_DEC_current",
    "g_star", "g_gal", "galaxies", "P_raw", "P_norm", "klasa",
]


@dataclass
class ImageResult:
    index: int
    token: int
    image_path: Path
    cache_hit: bool
    ra_deg: float
    dec_deg: float
    selected_fov_deg: float
    displayed_fov_deg: float
    auto_fov_used: bool
    resolved_galaxies: List[Tuple[str, float, float, float]]
    failed_galaxies: List[str]
    nearest_galaxy_name: Optional[str]
    nearest_galaxy_sep_deg: Optional[float]
    image_url: str
    error: Optional[str] = None


def normalize_column_name(name: str) -> str:
    return str(name).strip().lstrip("\ufeff")


def format_float(value: Any, digits: int = 3, fallback: str = "—") -> str:
    try:
        if pd.isna(value):
            return fallback
        x = float(value)
        return f"{x:.{digits}f}"
    except Exception:
        text = str(value).strip()
        return text if text else fallback


def sexagesimal_pair_to_degrees(ra_value: Any, dec_value: Any) -> Tuple[float, float]:
    """Parse RA/Dec columns produced by the probolism-search program."""
    ra_s = str(ra_value).strip()
    dec_s = str(dec_value).strip()
    if not ra_s or not dec_s or ra_s.lower() == "nan" or dec_s.lower() == "nan":
        raise ValueError("Empty RA/Dec coordinates.")

    # 1) Decimal degrees in both columns.
    try:
        ra_float = float(ra_s)
        dec_float = float(dec_s)
        return ra_float % 360.0, dec_float
    except Exception:
        pass

    # 2) Strings like 12h34m56.7s and +12d34m56.7s from astropy.to_string().
    try:
        coord = SkyCoord(f"{ra_s} {dec_s}", unit=(u.hourangle, u.deg), frame="icrs")
        return coord.ra.deg % 360.0, coord.dec.deg
    except Exception:
        pass

    # 3) Strings like 188.7 +12.3 in a single-ish format, or RA written with spaces.
    try:
        coord = SkyCoord(f"{ra_s} {dec_s}", frame="icrs")
        return coord.ra.deg % 360.0, coord.dec.deg
    except Exception as exc:
        raise ValueError(f"Cannot parse coordinates: RA={ra_s!r}, DEC={dec_s!r}") from exc


def row_to_center_degrees(row: pd.Series) -> Tuple[float, float]:
    columns = {normalize_column_name(c): c for c in row.index}

    # Prefer J2000/ICRS center columns from the source program.
    for ra_col, dec_col in [
        ("center_RA", "center_DEC"),
        ("ra", "dec"),
        ("RA", "DEC"),
        ("ra_deg", "dec_deg"),
        ("RA_deg", "DEC_deg"),
        ("center_RA_current", "center_DEC_current"),
    ]:
        if ra_col in columns and dec_col in columns:
            return sexagesimal_pair_to_degrees(row[columns[ra_col]], row[columns[dec_col]])

    raise ValueError(
        "No coordinate column pair was found. Expected columns such as center_RA and center_DEC."
    )


def center_constellation_name(ra_deg: float, dec_deg: float) -> str:
    try:
        coord = SkyCoord(ra_deg * u.deg, dec_deg * u.deg, frame="icrs")
        return str(get_constellation(coord, short_name=False))
    except Exception as exc:
        return f"unknown ({exc})"


def split_galaxy_names(galaxy_text: Any) -> List[str]:
    if galaxy_text is None or pd.isna(galaxy_text):
        return []
    text = str(galaxy_text).strip()
    if not text or text.lower() == "nan":
        return []
    parts = re.split(r"\s*;\s*|\s*,\s*(?=[A-Za-z]{1,5}\s*\d)", text)
    names: List[str] = []
    for part in parts:
        part = part.strip()
        if part and part.lower() != "nan" and part not in names:
            names.append(part)
    return names


def safe_filename_hash(payload: Dict[str, Any]) -> str:
    stable = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(stable.encode("utf-8")).hexdigest()[:24]


def build_hips2fits_url(
    endpoint: str,
    hips: str,
    ra_deg: float,
    dec_deg: float,
    fov_deg: float,
    width: int,
    height: int,
    image_format: str = "jpg",
) -> str:
    params = {
        "hips": hips,
        "width": int(width),
        "height": int(height),
        "projection": "TAN",
        "ra": f"{ra_deg:.9f}",
        "dec": f"{dec_deg:.9f}",
        "fov": f"{fov_deg:.6f}",
        "coordsys": "icrs",
        "rotation_angle": "0",
        "format": image_format,
        "min_cut": "0.5%",
        "max_cut": "99.5%",
        "stretch": "asinh",
    }
    return endpoint + "?" + urlencode(params)


def fetch_url_to_file(url: str, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = out_path.with_suffix(out_path.suffix + ".tmp")
    headers = {"User-Agent": "probolism-csv-browser/1.0"}
    with requests.get(url, timeout=REQUEST_TIMEOUT_SEC, headers=headers, stream=True) as response:
        response.raise_for_status()
        content_type = response.headers.get("content-type", "")
        if "text/html" in content_type.lower():
            # Usually means an error page instead of an image.
            text = response.text[:500]
            raise RuntimeError(f"The service returned HTML instead of an image: {text}")
        with tmp_path.open("wb") as f:
            for chunk in response.iter_content(chunk_size=1024 * 64):
                if chunk:
                    f.write(chunk)
    tmp_path.replace(out_path)


def is_valid_image_file(path: Path) -> bool:
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        with Image.open(path) as img:
            img.verify()
        return True
    except Exception:
        return False


def fetch_image_to_cache_with_retries(primary_url: str, mirror_url: str, image_path: Path) -> str:
    last_error = ""
    for attempt in range(1, BULK_DOWNLOAD_RETRIES + 1):
        for url in (primary_url, mirror_url):
            try:
                fetch_url_to_file(url, image_path)
                if is_valid_image_file(image_path):
                    return url
                last_error = "Downloaded file is not a readable image."
                try:
                    image_path.unlink()
                except Exception:
                    pass
            except Exception as exc:
                last_error = str(exc)
                try:
                    if image_path.exists() and not is_valid_image_file(image_path):
                        image_path.unlink()
                except Exception:
                    pass
        if attempt < BULK_DOWNLOAD_RETRIES:
            time.sleep(BULK_RETRY_DELAY_SEC * attempt)
    raise RuntimeError(last_error or "Image download failed.")


def angular_separation_deg(ra1: float, dec1: float, ra2: float, dec2: float) -> float:
    c1 = SkyCoord(ra1 * u.deg, dec1 * u.deg, frame="icrs")
    c2 = SkyCoord(ra2 * u.deg, dec2 * u.deg, frame="icrs")
    return float(c1.separation(c2).deg)


class GalaxyResolver:
    """Small persistent cache around SkyCoord.from_name/Sesame resolution."""

    def __init__(self, cache_dir: Path):
        self.cache_dir = cache_dir
        self.cache_path = cache_dir / "galaxy_name_resolutions.json"
        self._data: Dict[str, Any] = {}
        self._load()

    def _load(self) -> None:
        try:
            if self.cache_path.exists():
                self._data = json.loads(self.cache_path.read_text(encoding="utf-8"))
        except Exception:
            self._data = {}

    def _save(self) -> None:
        try:
            self.cache_dir.mkdir(parents=True, exist_ok=True)
            self.cache_path.write_text(
                json.dumps(self._data, ensure_ascii=False, indent=2, sort_keys=True),
                encoding="utf-8",
            )
        except Exception:
            pass

    @staticmethod
    def _variants(name: str) -> List[str]:
        name = name.strip()
        variants = [name]
        # Improve common RC3 forms such as NGC4440, IC123, PGC12345.
        m = re.match(r"^(NGC|IC|PGC|UGC|MCG)(\d.*)$", name, flags=re.IGNORECASE)
        if m:
            variants.append(f"{m.group(1).upper()} {m.group(2).strip()}")
        variants.append(name.replace("_", " "))
        out: List[str] = []
        for v in variants:
            v = re.sub(r"\s+", " ", v).strip()
            if v and v not in out:
                out.append(v)
        return out

    def resolve(self, name: str) -> Optional[Tuple[float, float]]:
        key = re.sub(r"\s+", " ", name.strip())
        if not key:
            return None
        cached = self._data.get(key)
        if isinstance(cached, dict) and cached.get("ok"):
            return float(cached["ra_deg"]), float(cached["dec_deg"])
        if isinstance(cached, dict) and cached.get("ok") is False:
            return None

        for variant in self._variants(key):
            try:
                coord = SkyCoord.from_name(variant, parse=True)
                ra_dec = (float(coord.ra.deg) % 360.0, float(coord.dec.deg))
                self._data[key] = {"ok": True, "name_used": variant, "ra_deg": ra_dec[0], "dec_deg": ra_dec[1]}
                self._save()
                return ra_dec
            except Exception:
                time.sleep(0.15)

        self._data[key] = {"ok": False, "failed_at": time.strftime("%Y-%m-%dT%H:%M:%S")}
        self._save()
        return None


class ProbolismCsvBrowser:
    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title(APP_TITLE)
        self.root.geometry("1180x900")
        self.root.minsize(960, 720)

        self.csv_path_var = tk.StringVar()
        self.cache_dir_var = tk.StringVar(value=str(Path.cwd() / DEFAULT_CACHE_DIR))
        self.fov_var = tk.StringVar(value="0.3x0.3")
        self.survey_var = tk.StringVar(value=SURVEY_CHOICES[0])
        self.auto_fit_var = tk.BooleanVar(value=False)
        self.clear_cache_on_exit_var = tk.BooleanVar(value=False)
        self.image_size_var = tk.IntVar(value=DEFAULT_IMAGE_SIZE_PX)

        self.records: Optional[pd.DataFrame] = None
        self.current_index = 0
        self.current_token = 0
        self.last_image_url = ""
        self.worker: Optional[threading.Thread] = None
        self.result_queue: "queue.Queue[ImageResult]" = queue.Queue()
        self.bulk_worker: Optional[threading.Thread] = None
        self.bulk_progress_queue: "queue.Queue[Dict[str, Any]]" = queue.Queue()
        self.bulk_loading = False
        self.bulk_stop_event = threading.Event()
        self.bulk_next_index = 0
        self.bulk_progress_var = tk.DoubleVar(value=0.0)
        self.bulk_progress_label_var = tk.StringVar(value="Image cache loading: not running.")
        self.selected_records: set[int] = set()
        self.selected_current_var = tk.BooleanVar(value=False)
        self.selection_label_var = tk.StringVar(value="Selected: 0")
        self.export_progress_queue: "queue.Queue[Dict[str, Any]]" = queue.Queue()
        self.export_worker: Optional[threading.Thread] = None
        self.export_running = False

        # Image display state for pan/zoom.
        self.base_image: Optional[Image.Image] = None
        self.canvas_image_tk: Optional[ImageTk.PhotoImage] = None
        self.image_item: Optional[int] = None
        self.canvas_text_item: Optional[int] = None
        self.fit_scale = 1.0
        self.zoom = 1.0
        self.pan_x = 0.0
        self.pan_y = 0.0
        self._drag_start: Optional[Tuple[int, int, float, float]] = None

        self._build_widgets()
        self._bind_navigation()
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)
        self.root.after(100, self._poll_result_queue)
        self.root.after(100, self._poll_bulk_progress_queue)
        self.root.after(100, self._poll_export_progress_queue)

    def _build_widgets(self) -> None:
        outer = ttk.Frame(self.root, padding=8)
        outer.pack(fill="both", expand=True)

        title_bar = ttk.Frame(outer)
        title_bar.pack(fill="x")
        ttk.Label(title_bar, text=APP_TITLE, font=("Segoe UI", 14, "bold")).pack(side="left")
        ttk.Button(title_bar, text="User guide", command=self.show_user_guide).pack(side="right")

        file_frame = ttk.LabelFrame(outer, text="CSV file and cache", padding=8)
        file_frame.pack(fill="x", pady=(8, 0))
        file_frame.columnconfigure(1, weight=1)

        ttk.Label(file_frame, text="CSV file:").grid(row=0, column=0, sticky="w", padx=(0, 6), pady=2)
        ttk.Entry(file_frame, textvariable=self.csv_path_var).grid(row=0, column=1, sticky="ew", pady=2)
        ttk.Button(file_frame, text="Choose CSV…", command=self.choose_csv).grid(row=0, column=2, padx=(6, 0), pady=2)
        ttk.Button(file_frame, text="Load", command=self.load_csv).grid(row=0, column=3, padx=(6, 0), pady=2)

        ttk.Label(file_frame, text="Cache folder:").grid(row=1, column=0, sticky="w", padx=(0, 6), pady=2)
        ttk.Entry(file_frame, textvariable=self.cache_dir_var).grid(row=1, column=1, sticky="ew", pady=2)
        ttk.Button(file_frame, text="Choose cache…", command=self.choose_cache).grid(row=1, column=2, padx=(6, 0), pady=2)
        ttk.Checkbutton(
            file_frame,
            text="Clear browser cache on exit",
            variable=self.clear_cache_on_exit_var,
        ).grid(row=1, column=3, sticky="w", padx=(6, 0), pady=2)

        options = ttk.LabelFrame(outer, text="Image options", padding=8)
        options.pack(fill="x", pady=(8, 0))

        ttk.Label(options, text="Selected field:").grid(row=0, column=0, sticky="w", padx=(0, 6))
        fov_box = ttk.Combobox(
            options,
            width=8,
            textvariable=self.fov_var,
            values=[f"{str(v).rstrip('0').rstrip('.')}x{str(v).rstrip('0').rstrip('.')}" for v in SUPPORTED_FOV_BASE],
            state="readonly",
        )
        fov_box.grid(row=0, column=1, sticky="w")
        fov_box.bind("<<ComboboxSelected>>", lambda _e: self.refresh_current())
        ttk.Label(options, text="degrees; the downloaded/displayed field is larger by 0.1°").grid(row=0, column=2, sticky="w", padx=(6, 18))

        ttk.Label(options, text="HiPS survey:").grid(row=0, column=3, sticky="w", padx=(0, 6))
        survey_box = ttk.Combobox(options, width=34, textvariable=self.survey_var, values=SURVEY_CHOICES)
        survey_box.grid(row=0, column=4, sticky="w")
        survey_box.bind("<<ComboboxSelected>>", lambda _e: self.refresh_current())

        ttk.Checkbutton(
            options,
            text="Auto: enlarge the field if resolved galaxy names require a larger area",
            variable=self.auto_fit_var,
            command=self.refresh_current,
        ).grid(row=1, column=0, columnspan=5, sticky="w", pady=(6, 0))

        ttk.Label(
            options,
            text='Image control: Ctrl + drag moves the image, Ctrl + mouse wheel zooms it. Use the "Reset image view" button to restore the original view.',
        ).grid(row=2, column=0, columnspan=5, sticky="w", pady=(6, 0))

        nav = ttk.Frame(outer)
        nav.pack(fill="x", pady=(8, 0))
        ttk.Button(nav, text="⟵ Previous", command=self.previous_record).pack(side="left")
        ttk.Button(nav, text="Next ⟶", command=self.next_record).pack(side="left", padx=(6, 0))
        ttk.Button(nav, text="Refresh / download again", command=lambda: self.refresh_current(force_download=True)).pack(side="left", padx=(12, 0))
        ttk.Button(nav, text="Open image URL", command=self.open_last_url).pack(side="left", padx=(6, 0))
        ttk.Button(nav, text="Reset image view", command=self.reset_image_view).pack(side="left", padx=(6, 0))
        self.bulk_button_frame = ttk.Frame(nav)
        self.bulk_button_frame.pack(side="left", padx=(12, 0))
        self.load_all_button = ttk.Button(
            self.bulk_button_frame,
            text="Load all images to cache",
            command=self.load_all_images_to_cache,
            width=24,
        )
        self.load_all_button.grid(row=0, column=0, sticky="ew")
        self.stop_load_button = ttk.Button(
            self.bulk_button_frame,
            text="Stop loading images",
            command=self.stop_loading_images,
            width=24,
        )
        self.stop_load_button.grid(row=1, column=0, sticky="ew", pady=(2, 0))
        self.stop_load_button.grid_remove()
        ttk.Checkbutton(
            nav,
            text="Selected record",
            variable=self.selected_current_var,
            command=self.toggle_current_selection,
        ).pack(side="left", padx=(12, 0))
        self.export_button = ttk.Button(nav, text="Export selected to JPG…", command=self.export_selected_records_to_jpg)
        self.export_button.pack(side="left", padx=(6, 0))
        ttk.Label(nav, textvariable=self.selection_label_var).pack(side="left", padx=(8, 0))

        self.count_label = ttk.Label(nav, text="No CSV file loaded.")
        self.count_label.pack(side="right")

        progress_frame = ttk.Frame(outer)
        progress_frame.pack(fill="x", pady=(6, 0))
        self.bulk_progress_bar = ttk.Progressbar(
            progress_frame,
            orient="horizontal",
            mode="determinate",
            maximum=100,
            variable=self.bulk_progress_var,
            length=260,
        )
        self.bulk_progress_bar.pack(side="left", fill="x", expand=False)
        ttk.Label(progress_frame, textvariable=self.bulk_progress_label_var, width=52, anchor="w").pack(side="left", fill="x", expand=True, padx=(8, 0))

        main = ttk.Panedwindow(outer, orient="horizontal")
        main.pack(fill="both", expand=True, pady=(8, 0))

        image_panel = ttk.Frame(main)
        main.add(image_panel, weight=4)
        image_panel.rowconfigure(0, weight=1)
        image_panel.columnconfigure(0, weight=1)

        self.image_canvas = tk.Canvas(image_panel, background="black", highlightthickness=0)
        self.image_canvas.grid(row=0, column=0, sticky="nsew")
        self.show_canvas_message("Load a CSV file to download the first image.")

        self.caption_var = tk.StringVar(value="")
        self.caption_label = ttk.Label(image_panel, textvariable=self.caption_var, anchor="center", justify="center")
        self.caption_label.grid(row=1, column=0, sticky="ew", pady=(6, 0))

        details_panel = ttk.LabelFrame(main, text="Record parameters", padding=8)
        main.add(details_panel, weight=1)
        details_panel.columnconfigure(0, weight=1)

        self.details_text = tk.Text(details_panel, width=40, height=26, wrap="word")
        self.details_text.grid(row=0, column=0, sticky="nsew")
        details_panel.rowconfigure(0, weight=1)
        details_scroll = ttk.Scrollbar(details_panel, orient="vertical", command=self.details_text.yview)
        details_scroll.grid(row=0, column=1, sticky="ns")
        self.details_text.configure(yscrollcommand=details_scroll.set)

        self.status_var = tk.StringVar(value="Ready.")
        ttk.Label(outer, textvariable=self.status_var, relief="sunken", anchor="w").pack(fill="x", pady=(8, 0))

    def _bind_navigation(self) -> None:
        self.root.bind("<Right>", lambda _e: self.next_record())
        self.root.bind("<Down>", lambda _e: self.next_record())
        self.root.bind("<Left>", lambda _e: self.previous_record())
        self.root.bind("<Up>", lambda _e: self.previous_record())
        self.root.bind("<MouseWheel>", self.on_mouse_wheel)
        self.root.bind("<Button-4>", self.on_linux_mouse_wheel_up)
        self.root.bind("<Button-5>", self.on_linux_mouse_wheel_down)
        self.image_canvas.bind("<Configure>", lambda _e: self.render_canvas_image())
        self.image_canvas.bind("<ButtonPress-1>", self.on_canvas_button_press)
        self.image_canvas.bind("<B1-Motion>", self.on_canvas_drag)
        self.image_canvas.bind("<ButtonRelease-1>", self.on_canvas_button_release)

    @staticmethod
    def event_has_ctrl(event: tk.Event) -> bool:
        return bool(getattr(event, "state", 0) & CTRL_MASK)

    def choose_csv(self) -> None:
        path = filedialog.askopenfilename(
            title="Choose a CSV file with probolism candidates",
            filetypes=[("CSV", "*.csv"), ("All files", "*.*")],
        )
        if path:
            self.csv_path_var.set(path)
            self.load_csv()

    def choose_cache(self) -> None:
        path = filedialog.askdirectory(title="Choose the cache folder for images")
        if path:
            self.cache_dir_var.set(path)
            self.refresh_current()

    def load_csv(self) -> None:
        path = Path(self.csv_path_var.get().strip().strip('"'))
        if not path.exists():
            messagebox.showerror("Error", "Choose an existing CSV file.")
            return
        try:
            df = pd.read_csv(path, encoding="utf-8-sig")
            df.columns = [normalize_column_name(c) for c in df.columns]
            if df.empty:
                raise ValueError("The CSV file is empty.")
            # Validate first usable coordinate row.
            _ = row_to_center_degrees(df.iloc[0])
            self.records = df.reset_index(drop=True)
            self.current_index = 0
            self.bulk_next_index = 0
            self.bulk_stop_event.clear()
            self.selected_records.clear()
            self.update_selection_widgets()
            self.count_label.configure(text=f"Records: {len(df)} | current: 1/{len(df)}")
            missing = [c for c in ["g_star", "g_gal", "P_raw", "P_norm", "klasa"] if c not in df.columns]
            if missing:
                self.status_var.set("CSV loaded, but these columns are missing: " + ", ".join(missing))
            else:
                self.status_var.set(f"Loaded {len(df)} records from {path.name}.")
            self.display_record()
        except Exception as exc:
            messagebox.showerror("Cannot load CSV", f"{exc}\n\n{traceback.format_exc(limit=2)}")

    def on_mouse_wheel(self, event: tk.Event) -> str:
        if self.event_has_ctrl(event):
            if getattr(event, "delta", 0) < 0:
                self.zoom_image(1 / 1.2)
            else:
                self.zoom_image(1.2)
            return "break"
        if getattr(event, "delta", 0) < 0:
            self.next_record()
        else:
            self.previous_record()
        return "break"

    def on_linux_mouse_wheel_up(self, event: tk.Event) -> str:
        if self.event_has_ctrl(event):
            self.zoom_image(1.2)
        else:
            self.previous_record()
        return "break"

    def on_linux_mouse_wheel_down(self, event: tk.Event) -> str:
        if self.event_has_ctrl(event):
            self.zoom_image(1 / 1.2)
        else:
            self.next_record()
        return "break"

    def on_canvas_button_press(self, event: tk.Event) -> str:
        if self.event_has_ctrl(event):
            self._drag_start = (event.x, event.y, self.pan_x, self.pan_y)
            return "break"
        self._drag_start = None
        return "break"

    def on_canvas_drag(self, event: tk.Event) -> str:
        if self._drag_start is None:
            return ""
        start_x, start_y, old_pan_x, old_pan_y = self._drag_start
        self.pan_x = old_pan_x + (event.x - start_x)
        self.pan_y = old_pan_y + (event.y - start_y)
        self.render_canvas_image()
        return "break"

    def on_canvas_button_release(self, _event: tk.Event) -> str:
        self._drag_start = None
        return "break"

    def zoom_image(self, factor: float) -> None:
        if self.base_image is None:
            return
        self.zoom = max(0.25, min(8.0, self.zoom * factor))
        self.render_canvas_image()

    def reset_image_view(self) -> None:
        self.zoom = 1.0
        self.pan_x = 0.0
        self.pan_y = 0.0
        self.render_canvas_image()

    def toggle_current_selection(self) -> None:
        if self.records is None or self.records.empty:
            self.selected_current_var.set(False)
            return
        if self.selected_current_var.get():
            self.selected_records.add(self.current_index)
            self.status_var.set(f"Record {self.current_index + 1} selected.")
        else:
            self.selected_records.discard(self.current_index)
            self.status_var.set(f"Record {self.current_index + 1} unselected.")
        self.update_selection_widgets()

    def update_selection_widgets(self) -> None:
        if self.records is None or self.records.empty:
            self.selected_current_var.set(False)
            self.selection_label_var.set("Selected: 0")
            return
        self.selected_current_var.set(self.current_index in self.selected_records)
        self.selection_label_var.set(f"Selected: {len(self.selected_records)}")

    def show_canvas_message(self, text: str) -> None:
        self.image_canvas.delete("all") if hasattr(self, "image_canvas") else None
        if not hasattr(self, "image_canvas"):
            return
        w = max(400, self.image_canvas.winfo_width())
        h = max(300, self.image_canvas.winfo_height())
        self.canvas_text_item = self.image_canvas.create_text(
            w / 2,
            h / 2,
            text=text,
            fill="white",
            width=max(300, w - 80),
            justify="center",
        )
        self.image_item = None

    def render_canvas_image(self) -> None:
        if self.base_image is None or not hasattr(self, "image_canvas"):
            return
        canvas_w = max(10, self.image_canvas.winfo_width())
        canvas_h = max(10, self.image_canvas.winfo_height())
        img_w, img_h = self.base_image.size
        self.fit_scale = min((canvas_w - 20) / img_w, (canvas_h - 20) / img_h, 1.0)
        scale = max(0.05, self.fit_scale * self.zoom)
        new_w = max(1, int(img_w * scale))
        new_h = max(1, int(img_h * scale))
        rendered = self.base_image.resize((new_w, new_h), Image.LANCZOS)
        self.canvas_image_tk = ImageTk.PhotoImage(rendered)
        self.image_canvas.delete("all")
        self.image_item = self.image_canvas.create_image(
            canvas_w / 2 + self.pan_x,
            canvas_h / 2 + self.pan_y,
            image=self.canvas_image_tk,
            anchor="center",
        )

    def next_record(self) -> None:
        if self.records is None or self.records.empty:
            return
        if self.current_index >= len(self.records) - 1:
            self.root.bell()
            self.current_index = 0
        else:
            self.current_index += 1
        self.display_record()

    def previous_record(self) -> None:
        if self.records is None or self.records.empty:
            return
        if self.current_index <= 0:
            self.root.bell()
            self.current_index = len(self.records) - 1
        else:
            self.current_index -= 1
        self.display_record()

    def refresh_current(self, force_download: bool = False) -> None:
        if self.records is not None and not self.records.empty:
            self.display_record(force_download=force_download)

    def load_all_images_to_cache(self) -> None:
        if self.records is None or self.records.empty:
            messagebox.showinfo("No CSV file loaded", "Load a CSV file first.")
            return
        if self.bulk_loading:
            messagebox.showinfo("Cache loading already running", "The browser is already loading images to cache.")
            return

        records_copy = self.records.copy().reset_index(drop=True)
        selected_fov = self.get_selected_fov()
        survey = self.survey_var.get().strip() or SURVEY_CHOICES[0]
        auto_fit = bool(self.auto_fit_var.get())
        cache_dir = Path(self.cache_dir_var.get().strip().strip('"') or DEFAULT_CACHE_DIR)
        width = int(self.image_size_var.get() or DEFAULT_IMAGE_SIZE_PX)
        start_index = max(0, min(int(self.bulk_next_index), len(records_copy)))
        if start_index >= len(records_copy):
            start_index = 0
            self.bulk_next_index = 0

        self.bulk_loading = True
        self.bulk_stop_event.clear()
        self.load_all_button.configure(state="disabled")
        self.stop_load_button.configure(state="normal", text="Stop loading images")
        self.stop_load_button.grid()
        self.bulk_progress_var.set(float(start_index))
        self.bulk_progress_label_var.set(f"Image cache loading: {start_index}/{len(records_copy)}")
        if start_index:
            self.status_var.set(f"Resuming image cache loading from record {start_index + 1}…")
        else:
            self.status_var.set("Loading all images to cache…")

        args = (records_copy, selected_fov, survey, auto_fit, cache_dir, width, start_index, self.bulk_stop_event)
        self.bulk_worker = threading.Thread(target=self._worker_load_all_images_to_cache, args=args, daemon=True)
        self.bulk_worker.start()

    def stop_loading_images(self) -> None:
        if not self.bulk_loading:
            return
        self.bulk_stop_event.set()
        self.stop_load_button.configure(state="disabled", text="Stopping…")
        self.status_var.set("Stopping image cache loading after the current image…")

    def _worker_load_all_images_to_cache(
        self,
        records: pd.DataFrame,
        selected_fov: float,
        survey: str,
        auto_fit: bool,
        cache_dir: Path,
        width: int,
        start_index: int,
        stop_event: threading.Event,
    ) -> None:
        total = len(records)
        errors = 0
        last_done = start_index
        cache_dir.mkdir(parents=True, exist_ok=True)
        self.bulk_progress_queue.put({"kind": "start", "total": total, "start_index": start_index})

        for absolute_index in range(start_index, total):
            if stop_event.is_set():
                self.bulk_progress_queue.put({
                    "kind": "stopped",
                    "done": last_done,
                    "total": total,
                    "errors": errors,
                    "next_index": last_done,
                })
                return

            row = records.iloc[absolute_index]
            done = absolute_index + 1
            latest_error = ""
            try:
                ra_deg, dec_deg = row_to_center_degrees(row)
                displayed_fov = selected_fov + DISPLAY_MARGIN_DEG

                if auto_fit:
                    resolved: List[Tuple[str, float, float, float]] = []
                    galaxy_names = split_galaxy_names(row.get("galaxies", ""))
                    if galaxy_names:
                        resolver = GalaxyResolver(cache_dir)
                        for name in galaxy_names:
                            if stop_event.is_set():
                                break
                            coords = resolver.resolve(name)
                            if coords is None:
                                continue
                            sep = angular_separation_deg(ra_deg, dec_deg, coords[0], coords[1])
                            resolved.append((name, coords[0], coords[1], sep))
                    if resolved:
                        max_sep = max(item[3] for item in resolved)
                        needed = 2.0 * (max_sep + AUTO_GALAXY_MARGIN_DEG)
                        if needed > displayed_fov:
                            displayed_fov = needed

                if stop_event.is_set():
                    self.bulk_progress_queue.put({
                        "kind": "stopped",
                        "done": last_done,
                        "total": total,
                        "errors": errors,
                        "next_index": last_done,
                    })
                    return

                height = width
                payload = {
                    "service": "hips2fits",
                    "hips": survey,
                    "ra_deg": round(ra_deg, 7),
                    "dec_deg": round(dec_deg, 7),
                    "fov_deg": round(displayed_fov, 5),
                    "width": width,
                    "height": height,
                    "projection": "TAN",
                    "format": "jpg",
                    "stretch": "asinh",
                    "record_index": absolute_index + 1,
                }
                cache_key = safe_filename_hash(payload)
                image_path = cache_dir / f"probolism_{cache_key}.jpg"
                meta_path = cache_dir / f"probolism_{cache_key}.json"
                image_url = build_hips2fits_url(HIPS2FITS_PRIMARY, survey, ra_deg, dec_deg, displayed_fov, width, height, "jpg")

                if not is_valid_image_file(image_path):
                    if image_path.exists():
                        try:
                            image_path.unlink()
                        except Exception:
                            pass
                    mirror_url = build_hips2fits_url(HIPS2FITS_MIRROR, survey, ra_deg, dec_deg, displayed_fov, width, height, "jpg")
                    image_url = fetch_image_to_cache_with_retries(image_url, mirror_url, image_path)
                    meta_path.write_text(
                        json.dumps({**payload, "url": image_url, "created_at": time.strftime("%Y-%m-%dT%H:%M:%S")}, indent=2),
                        encoding="utf-8",
                    )
            except Exception as exc:
                errors += 1
                latest_error = str(exc)

            last_done = done
            self.bulk_progress_queue.put({
                "kind": "progress",
                "done": done,
                "total": total,
                "errors": errors,
                "latest_error": latest_error,
            })

        self.bulk_progress_queue.put({
            "kind": "done",
            "total": total,
            "errors": errors,
        })

    def _poll_bulk_progress_queue(self) -> None:
        try:
            while True:
                item = self.bulk_progress_queue.get_nowait()
                kind = item.get("kind")
                if kind == "start":
                    total = int(item.get("total", 1))
                    start_index = int(item.get("start_index", 0))
                    self.bulk_progress_bar.configure(maximum=max(1, total))
                    self.bulk_progress_var.set(float(start_index))
                elif kind == "progress":
                    done = int(item.get("done", 0))
                    total = int(item.get("total", 0))
                    errors = int(item.get("errors", 0))
                    latest_error = str(item.get("latest_error", "") or "")
                    self.bulk_next_index = min(done, total)
                    self.bulk_progress_var.set(float(done))
                    self.bulk_progress_label_var.set(
                        f"Image cache loading: {done}/{total} | errors: {errors}"
                    )
                    if latest_error:
                        self.status_var.set(
                            f"Loading images to cache: {done}/{total}. Errors: {errors}. Last error: {latest_error[:160]}"
                        )
                    else:
                        self.status_var.set(
                            f"Loading images to cache: {done}/{total}. Errors: {errors}."
                        )
                elif kind == "stopped":
                    done = int(item.get("done", 0))
                    total = int(item.get("total", 0))
                    errors = int(item.get("errors", 0))
                    next_index = int(item.get("next_index", done))
                    self.bulk_next_index = max(0, min(next_index, total))
                    self.bulk_progress_var.set(float(done))
                    self.bulk_progress_label_var.set(
                        f"Image cache loading stopped: {done}/{total} | errors: {errors}"
                    )
                    self.status_var.set(
                        f"Image cache loading stopped. Next load will resume from record {self.bulk_next_index + 1 if self.bulk_next_index < total else 1}."
                    )
                    self.bulk_loading = False
                    self.load_all_button.configure(state="normal")
                    self.stop_load_button.grid_remove()
                elif kind == "done":
                    total = int(item.get("total", 0))
                    errors = int(item.get("errors", 0))
                    self.bulk_next_index = 0
                    self.bulk_progress_var.set(float(total))
                    self.bulk_progress_label_var.set(
                        f"Image cache loading complete: {total}/{total} | errors: {errors}"
                    )
                    self.status_var.set(
                        f"Image cache loading complete. Processed: {total}/{total}. Errors: {errors}."
                    )
                    self.bulk_loading = False
                    self.load_all_button.configure(state="normal")
                    self.stop_load_button.grid_remove()
        except queue.Empty:
            pass
        self.root.after(100, self._poll_bulk_progress_queue)

    def get_selected_fov(self) -> float:
        try:
            value_text = self.fov_var.get().strip().lower().replace("×", "x")
            value = float(value_text.split("x", 1)[0])
            if value not in SUPPORTED_FOV_BASE:
                # Keep custom typed values sane, although the combobox is readonly by default.
                value = min(SUPPORTED_FOV_BASE, key=lambda x: abs(x - value))
            return value
        except Exception:
            return 0.3

    def display_record(self, force_download: bool = False) -> None:
        if self.records is None or self.records.empty:
            return
        row = self.records.iloc[self.current_index]
        self.current_token += 1
        token = self.current_token
        self.count_label.configure(text=f"Records: {len(self.records)} | current: {self.current_index + 1}/{len(self.records)}")
        self.update_selection_widgets()
        self.details_text.delete("1.0", "end")
        self.details_text.insert("end", self.format_record_details(row, nearest_galaxy_info="resolving…"))
        self.base_image = None
        self.canvas_image_tk = None
        self.show_canvas_message("Loading image…")
        self.caption_var.set("")
        self.status_var.set("Loading image from cache or from the internet…")
        self.zoom = 1.0
        self.pan_x = 0.0
        self.pan_y = 0.0

        args = (self.current_index, token, row.copy(), force_download)
        self.worker = threading.Thread(target=self._worker_load_image, args=args, daemon=True)
        self.worker.start()

    def format_record_details(
        self,
        row: pd.Series,
        nearest_galaxy_info: str = "resolving…",
        record_index: Optional[int] = None,
        galaxies_inline: bool = False,
    ) -> str:
        shown_index = self.current_index if record_index is None else record_index
        try:
            ra_deg, dec_deg = row_to_center_degrees(row)
            center = f"RA={ra_deg:.6f}°, DEC={dec_deg:.6f}°"
            constellation = center_constellation_name(ra_deg, dec_deg)
        except Exception as exc:
            center = f"Coordinate error: {exc}"
            constellation = "unknown"

        lines = [
            f"Record: {shown_index + 1}",
            f"Field center: {center}",
            f"Constellation: {constellation}",
            f"Nearest galaxy to field center: {nearest_galaxy_info}",
            "",
            f"g_star: {row.get('g_star', '—')}",
            f"g_gal:  {row.get('g_gal', '—')}",
            f"P_raw:  {format_float(row.get('P_raw'), 4)}",
            f"P_norm: {format_float(row.get('P_norm'), 4)}",
            f"class (klasa): {row.get('klasa', '—')}",
            "",
            f"center_RA:  {row.get('center_RA', '—')}",
            f"center_DEC: {row.get('center_DEC', '—')}",
        ]
        if "center_RA_current" in row.index or "center_DEC_current" in row.index:
            lines.extend([
                f"center_RA_current:  {row.get('center_RA_current', '—')}",
                f"center_DEC_current: {row.get('center_DEC_current', '—')}",
            ])
        galaxy_names = split_galaxy_names(row.get("galaxies", ""))
        lines.extend(["", f"Galaxies in this row ({len(galaxy_names)}):"])
        if galaxy_names:
            if galaxies_inline:
                lines.append("  " + ", ".join(galaxy_names))
            else:
                lines.extend([f"  • {name}" for name in galaxy_names])
        else:
            lines.append("  —")
        return "\n".join(str(x) for x in lines)

    def _worker_load_image(self, index: int, token: int, row: pd.Series, force_download: bool) -> None:
        try:
            ra_deg, dec_deg = row_to_center_degrees(row)
            selected_fov = self.get_selected_fov()
            displayed_fov = selected_fov + DISPLAY_MARGIN_DEG
            auto_fov_used = False
            resolved: List[Tuple[str, float, float, float]] = []
            failed: List[str] = []
            cache_dir = Path(self.cache_dir_var.get().strip().strip('"') or DEFAULT_CACHE_DIR)
            cache_dir.mkdir(parents=True, exist_ok=True)

            galaxy_names = split_galaxy_names(row.get("galaxies", ""))
            if galaxy_names:
                resolver = GalaxyResolver(cache_dir)
                for name in galaxy_names:
                    coords = resolver.resolve(name)
                    if coords is None:
                        failed.append(name)
                        continue
                    sep = angular_separation_deg(ra_deg, dec_deg, coords[0], coords[1])
                    resolved.append((name, coords[0], coords[1], sep))

            nearest_galaxy_name: Optional[str] = None
            nearest_galaxy_sep_deg: Optional[float] = None
            if resolved:
                nearest = min(resolved, key=lambda item: item[3])
                nearest_galaxy_name = nearest[0]
                nearest_galaxy_sep_deg = nearest[3]

            if self.auto_fit_var.get() and resolved:
                max_sep = max(item[3] for item in resolved)
                needed = 2.0 * (max_sep + AUTO_GALAXY_MARGIN_DEG)
                if needed > displayed_fov:
                    displayed_fov = needed
                    auto_fov_used = True

            hips = self.survey_var.get().strip() or SURVEY_CHOICES[0]
            width = int(self.image_size_var.get() or DEFAULT_IMAGE_SIZE_PX)
            height = width
            payload = {
                "service": "hips2fits",
                "hips": hips,
                "ra_deg": round(ra_deg, 7),
                "dec_deg": round(dec_deg, 7),
                "fov_deg": round(displayed_fov, 5),
                "width": width,
                "height": height,
                "projection": "TAN",
                "format": "jpg",
                "stretch": "asinh",
                "record_index": index + 1,
            }
            cache_key = safe_filename_hash(payload)
            image_path = cache_dir / f"probolism_{cache_key}.jpg"
            meta_path = cache_dir / f"probolism_{cache_key}.json"
            image_url = build_hips2fits_url(HIPS2FITS_PRIMARY, hips, ra_deg, dec_deg, displayed_fov, width, height, "jpg")
            cache_hit = is_valid_image_file(image_path) and not force_download

            if not cache_hit:
                if image_path.exists():
                    try:
                        image_path.unlink()
                    except Exception:
                        pass
                try:
                    fetch_url_to_file(image_url, image_path)
                except Exception:
                    mirror_url = build_hips2fits_url(HIPS2FITS_MIRROR, hips, ra_deg, dec_deg, displayed_fov, width, height, "jpg")
                    fetch_url_to_file(mirror_url, image_path)
                    image_url = mirror_url
                meta_path.write_text(
                    json.dumps({**payload, "url": image_url, "created_at": time.strftime("%Y-%m-%dT%H:%M:%S")}, indent=2),
                    encoding="utf-8",
                )

            self.result_queue.put(ImageResult(
                index=index,
                token=token,
                image_path=image_path,
                cache_hit=cache_hit,
                ra_deg=ra_deg,
                dec_deg=dec_deg,
                selected_fov_deg=selected_fov,
                displayed_fov_deg=displayed_fov,
                auto_fov_used=auto_fov_used,
                resolved_galaxies=resolved,
                failed_galaxies=failed,
                nearest_galaxy_name=nearest_galaxy_name,
                nearest_galaxy_sep_deg=nearest_galaxy_sep_deg,
                image_url=image_url,
            ))
        except Exception as exc:
            self.result_queue.put(ImageResult(
                index=index,
                token=token,
                image_path=Path(),
                cache_hit=False,
                ra_deg=float("nan"),
                dec_deg=float("nan"),
                selected_fov_deg=self.get_selected_fov(),
                displayed_fov_deg=self.get_selected_fov() + DISPLAY_MARGIN_DEG,
                auto_fov_used=False,
                resolved_galaxies=[],
                failed_galaxies=[],
                nearest_galaxy_name=None,
                nearest_galaxy_sep_deg=None,
                image_url="",
                error=f"{exc}\n\n{traceback.format_exc(limit=4)}",
            ))

    def _poll_result_queue(self) -> None:
        try:
            while True:
                result = self.result_queue.get_nowait()
                if result.token != self.current_token:
                    continue
                self._apply_image_result(result)
        except queue.Empty:
            pass
        self.root.after(100, self._poll_result_queue)

    def _apply_image_result(self, result: ImageResult) -> None:
        if result.error:
            self.status_var.set("Image download error.")
            self.base_image = None
            self.show_canvas_message(result.error)
            self.caption_var.set("")
            return

        try:
            img = Image.open(result.image_path).convert("RGB")
            img = self._draw_overlays(img, result)
            self.base_image = img
            self.zoom = 1.0
            self.pan_x = 0.0
            self.pan_y = 0.0
            self.render_canvas_image()
            self.last_image_url = result.image_url
            if self.records is not None and not self.records.empty and result.index == self.current_index:
                current_row = self.records.iloc[self.current_index]
                self.details_text.delete("1.0", "end")
                self.details_text.insert("end", self.format_record_details(current_row, self.format_nearest_galaxy(result, current_row)))

            cache_text = "cache" if result.cache_hit else "internet → cache"
            auto_text = "; auto-fit active" if result.auto_fov_used else ""
            unresolved_text = ""
            if self.auto_fit_var.get() and result.failed_galaxies:
                unresolved_text = f"; unresolved galaxy names: {len(result.failed_galaxies)}"
            self.caption_var.set(
                f"Selected field: {result.selected_fov_deg:.1f}° × {result.selected_fov_deg:.1f}°. "
                f"Displayed/downloaded: {result.displayed_fov_deg:.2f}° × {result.displayed_fov_deg:.2f}° "
                f"(selected field + 0.1° margin{auto_text}). Source: {cache_text}{unresolved_text}."
            )
            self.status_var.set(
                f"Record {result.index + 1}: RA={result.ra_deg:.6f}°, DEC={result.dec_deg:.6f}°, "
                f"FOV={result.displayed_fov_deg:.2f}°. Ctrl+drag pans, Ctrl+wheel zooms. Use the Reset image view button to restore the original view."
            )
        except Exception as exc:
            self.status_var.set("Image display error.")
            self.base_image = None
            self.show_canvas_message(f"Cannot display the image file:\n{exc}")

    def format_nearest_galaxy(self, result: ImageResult, row: pd.Series) -> str:
        galaxy_names = split_galaxy_names(row.get("galaxies", ""))
        if not galaxy_names:
            return "not available — no galaxies listed in this row"
        if result.nearest_galaxy_name and result.nearest_galaxy_sep_deg is not None:
            return f"{result.nearest_galaxy_name} ({result.nearest_galaxy_sep_deg:.4f}° from center)"
        if result.failed_galaxies:
            return "not available — galaxy names could not be resolved"
        return "not available"

    def _draw_overlays(self, img: Image.Image, result: ImageResult, draw_galaxy_labels: Optional[bool] = None) -> Image.Image:
        """Draw a simple central crosshair and optional resolved-galaxy labels."""
        draw = ImageDraw.Draw(img)
        w, h = img.size
        cx, cy = w // 2, h // 2
        # Neutral white/black crosshair for the exact CSV centre.
        r = max(8, min(w, h) // 80)
        draw.line((cx - r, cy, cx + r, cy), fill=(255, 255, 255), width=1)
        draw.line((cx, cy - r, cx, cy + r), fill=(255, 255, 255), width=1)
        draw.ellipse((cx - 2, cy - 2, cx + 2, cy + 2), outline=(0, 0, 0), width=1)

        if draw_galaxy_labels is None:
            draw_galaxy_labels = bool(self.auto_fit_var.get())
        if not (draw_galaxy_labels and result.resolved_galaxies):
            return img

        # Approximate tangent-plane placement. Good enough for small FoV preview.
        deg_per_px = result.displayed_fov_deg / float(min(w, h))
        center_dec_rad = math.radians(result.dec_deg)
        for name, ra, dec, _sep in result.resolved_galaxies:
            dra = ((ra - result.ra_deg + 540.0) % 360.0) - 180.0
            x = cx - (dra * math.cos(center_dec_rad)) / deg_per_px
            y = cy - (dec - result.dec_deg) / deg_per_px
            if -20 <= x <= w + 20 and -20 <= y <= h + 20:
                draw.ellipse((x - 5, y - 5, x + 5, y + 5), outline=(255, 255, 0), width=2)
                draw.text((x + 7, y + 4), name, fill=(255, 255, 0))
        return img

    def export_selected_records_to_jpg(self) -> None:
        if self.records is None or self.records.empty:
            messagebox.showinfo("No CSV file loaded", "Load a CSV file first.")
            return
        valid_indices = sorted(i for i in self.selected_records if 0 <= i < len(self.records))
        if not valid_indices:
            messagebox.showinfo("No selected records", "Select at least one record first. Use the \"Selected record\" checkbox.")
            return
        if self.export_running:
            messagebox.showinfo("Export already running", "The browser is already exporting selected records.")
            return
        out_path_str = filedialog.asksaveasfilename(
            title="Choose base name for exported JPG files",
            defaultextension=".jpg",
            filetypes=[("JPEG image", "*.jpg;*.jpeg"), ("All files", "*.*")],
        )
        if not out_path_str:
            return
        out_path = Path(out_path_str)
        records_copy = self.records.copy().reset_index(drop=True)
        selected_fov = self.get_selected_fov()
        survey = self.survey_var.get().strip() or SURVEY_CHOICES[0]
        auto_fit = bool(self.auto_fit_var.get())
        cache_dir = Path(self.cache_dir_var.get().strip().strip('"') or DEFAULT_CACHE_DIR)
        width = int(self.image_size_var.get() or DEFAULT_IMAGE_SIZE_PX)

        self.export_running = True
        self.export_button.configure(state="disabled")
        self.status_var.set(f"Exporting {len(valid_indices)} selected records to JPG…")
        args = (records_copy, valid_indices, selected_fov, survey, auto_fit, cache_dir, width, out_path)
        self.export_worker = threading.Thread(target=self._worker_export_selected_records_to_jpg, args=args, daemon=True)
        self.export_worker.start()

    def _image_result_for_export(
        self,
        index: int,
        row: pd.Series,
        selected_fov: float,
        survey: str,
        auto_fit: bool,
        cache_dir: Path,
        width: int,
    ) -> ImageResult:
        ra_deg, dec_deg = row_to_center_degrees(row)
        displayed_fov = selected_fov + DISPLAY_MARGIN_DEG
        auto_fov_used = False
        resolved: List[Tuple[str, float, float, float]] = []
        failed: List[str] = []
        cache_dir.mkdir(parents=True, exist_ok=True)

        galaxy_names = split_galaxy_names(row.get("galaxies", ""))
        if galaxy_names:
            resolver = GalaxyResolver(cache_dir)
            for name in galaxy_names:
                coords = resolver.resolve(name)
                if coords is None:
                    failed.append(name)
                    continue
                sep = angular_separation_deg(ra_deg, dec_deg, coords[0], coords[1])
                resolved.append((name, coords[0], coords[1], sep))

        nearest_galaxy_name: Optional[str] = None
        nearest_galaxy_sep_deg: Optional[float] = None
        if resolved:
            nearest = min(resolved, key=lambda item: item[3])
            nearest_galaxy_name = nearest[0]
            nearest_galaxy_sep_deg = nearest[3]

        if auto_fit and resolved:
            max_sep = max(item[3] for item in resolved)
            needed = 2.0 * (max_sep + AUTO_GALAXY_MARGIN_DEG)
            if needed > displayed_fov:
                displayed_fov = needed
                auto_fov_used = True

        height = width
        payload = {
            "service": "hips2fits",
            "hips": survey,
            "ra_deg": round(ra_deg, 7),
            "dec_deg": round(dec_deg, 7),
            "fov_deg": round(displayed_fov, 5),
            "width": width,
            "height": height,
            "projection": "TAN",
            "format": "jpg",
            "stretch": "asinh",
            "record_index": index + 1,
        }
        cache_key = safe_filename_hash(payload)
        image_path = cache_dir / f"probolism_{cache_key}.jpg"
        meta_path = cache_dir / f"probolism_{cache_key}.json"
        image_url = build_hips2fits_url(HIPS2FITS_PRIMARY, survey, ra_deg, dec_deg, displayed_fov, width, height, "jpg")
        cache_hit = is_valid_image_file(image_path)

        if not cache_hit:
            if image_path.exists():
                try:
                    image_path.unlink()
                except Exception:
                    pass
            mirror_url = build_hips2fits_url(HIPS2FITS_MIRROR, survey, ra_deg, dec_deg, displayed_fov, width, height, "jpg")
            image_url = fetch_image_to_cache_with_retries(image_url, mirror_url, image_path)
            meta_path.write_text(
                json.dumps({**payload, "url": image_url, "created_at": time.strftime("%Y-%m-%dT%H:%M:%S")}, indent=2),
                encoding="utf-8",
            )

        return ImageResult(
            index=index,
            token=0,
            image_path=image_path,
            cache_hit=cache_hit,
            ra_deg=ra_deg,
            dec_deg=dec_deg,
            selected_fov_deg=selected_fov,
            displayed_fov_deg=displayed_fov,
            auto_fov_used=auto_fov_used,
            resolved_galaxies=resolved,
            failed_galaxies=failed,
            nearest_galaxy_name=nearest_galaxy_name,
            nearest_galaxy_sep_deg=nearest_galaxy_sep_deg,
            image_url=image_url,
        )

    @staticmethod
    def _export_font() -> ImageFont.ImageFont:
        for name in ("arial.ttf", "segoeui.ttf", "DejaVuSans.ttf"):
            try:
                return ImageFont.truetype(name, 16)
            except Exception:
                pass
        return ImageFont.load_default()

    @staticmethod
    def _wrap_text_for_export(text: str, width_chars: int = 68) -> List[str]:
        wrapped: List[str] = []
        for raw_line in text.splitlines():
            if not raw_line:
                wrapped.append("")
                continue
            indent = len(raw_line) - len(raw_line.lstrip(" "))
            prefix = " " * indent
            words = raw_line.split(" ")
            line = ""
            for word in words:
                candidate = word if not line else line + " " + word
                if len(candidate) <= width_chars:
                    line = candidate
                else:
                    if line:
                        wrapped.append(line)
                    line = prefix + word if prefix and not word.startswith(prefix) else word
            if line:
                wrapped.append(line)
        return wrapped

    def _build_export_record_block(self, image: Image.Image, details: str, record_number: int) -> Image.Image:
        font = self._export_font()
        line_height = 21
        margin = 18
        gap = 18
        image_width = 420
        if image.width != image_width:
            ratio = image_width / float(image.width)
            image = image.resize((image_width, max(1, int(image.height * ratio))), Image.LANCZOS)
        text_lines = self._wrap_text_for_export(details, width_chars=72)
        text_width = 630
        text_height = max(image.height, margin * 2 + line_height * (len(text_lines) + 1))
        block = Image.new("RGB", (margin * 2 + image_width + gap + text_width, text_height), "white")
        draw = ImageDraw.Draw(block)
        block.paste(image, (margin, margin))
        x = margin + image_width + gap
        y = margin
        draw.text((x, y), f"Selected probolism record {record_number}", fill="black", font=font)
        y += line_height + 8
        for line in text_lines:
            safe_line = line.replace("—", "-").replace("×", "x").replace("°", " deg").replace("•", "*")
            draw.text((x, y), safe_line, fill="black", font=font)
            y += line_height
        return block

    def _worker_export_selected_records_to_jpg(
        self,
        records: pd.DataFrame,
        indices: List[int],
        selected_fov: float,
        survey: str,
        auto_fit: bool,
        cache_dir: Path,
        width: int,
        out_path: Path,
    ) -> None:
        blocks: List[Tuple[Image.Image, int]] = []
        saved_paths: List[Path] = []
        try:
            total = len(indices)
            for done, index in enumerate(indices, start=1):
                self.export_progress_queue.put({"kind": "progress", "done": done, "total": total, "record": index + 1})
                row = records.iloc[index]
                result = self._image_result_for_export(index, row, selected_fov, survey, auto_fit, cache_dir, width)
                img = Image.open(result.image_path).convert("RGB")
                img = self._draw_overlays(img, result, draw_galaxy_labels=auto_fit)
                nearest_info = self.format_nearest_galaxy(result, row)
                galaxy_count = len(split_galaxy_names(row.get("galaxies", "")))
                details = self.format_record_details(row, nearest_info, record_index=index, galaxies_inline=(galaxy_count > 5))
                blocks.append((self._build_export_record_block(img, details, index + 1), galaxy_count))

            if not blocks:
                raise RuntimeError("No record blocks were created.")
            spacing = 24
            out_path.parent.mkdir(parents=True, exist_ok=True)
            stem = out_path.stem or "selected_probolisms"
            suffix = out_path.suffix if out_path.suffix.lower() in (".jpg", ".jpeg") else ".jpg"
            csv_path = out_path.with_name(f"{stem}.csv")
            records.iloc[indices].to_csv(csv_path, index=False, encoding="utf-8-sig")

            groups: List[List[Image.Image]] = []
            current_group: List[Image.Image] = []
            for block, galaxy_count in blocks:
                long_galaxy_list = galaxy_count > 5
                if long_galaxy_list:
                    if current_group:
                        groups.append(current_group)
                        current_group = []
                    groups.append([block])
                else:
                    current_group.append(block)
                    if len(current_group) == 2:
                        groups.append(current_group)
                        current_group = []
            if current_group:
                groups.append(current_group)

            for file_number, group in enumerate(groups, start=1):
                final_width = max(block.width for block in group)
                final_height = sum(block.height for block in group) + spacing * (len(group) - 1)
                final_img = Image.new("RGB", (final_width, final_height), "white")
                y = 0
                for block in group:
                    final_img.paste(block, (0, y))
                    y += block.height + spacing
                page_path = out_path.with_name(f"{stem}_{file_number:03d}{suffix}")
                final_img.save(page_path, quality=92)
                saved_paths.append(page_path)

            self.export_progress_queue.put({
                "kind": "done",
                "path": str(saved_paths[0]) if saved_paths else str(out_path),
                "folder": str(out_path.parent),
                "csv_path": str(csv_path),
                "count": len(blocks),
                "file_count": len(saved_paths),
            })
        except Exception as exc:
            self.export_progress_queue.put({"kind": "error", "error": f"{exc}\n\n{traceback.format_exc(limit=4)}"})

    def _poll_export_progress_queue(self) -> None:
        try:
            while True:
                item = self.export_progress_queue.get_nowait()
                kind = item.get("kind")
                if kind == "progress":
                    done = int(item.get("done", 0))
                    total = int(item.get("total", 0))
                    record = int(item.get("record", 0))
                    self.status_var.set(f"Exporting selected records to JPG: {done}/{total} (record {record})…")
                elif kind == "done":
                    self.export_running = False
                    self.export_button.configure(state="normal")
                    path = str(item.get("path", ""))
                    folder = str(item.get("folder", ""))
                    count = int(item.get("count", 0))
                    file_count = int(item.get("file_count", 1))
                    csv_path = str(item.get("csv_path", ""))
                    self.status_var.set(f"Export complete. Saved {count} selected records in {file_count} JPG files and one CSV file: {folder}")
                    messagebox.showinfo(
                        "Export complete",
                        f"Saved {count} selected records in {file_count} JPG files and one CSV file.\n\n"
                        f"Folder:\n{folder}\n\nFirst JPG file:\n{path}\n\nCSV file:\n{csv_path}",
                    )
                elif kind == "error":
                    self.export_running = False
                    self.export_button.configure(state="normal")
                    error = str(item.get("error", "Unknown export error."))
                    self.status_var.set("Export error.")
                    messagebox.showerror("Export error", error)
        except queue.Empty:
            pass
        self.root.after(100, self._poll_export_progress_queue)

    def open_last_url(self) -> None:
        if self.last_image_url:
            webbrowser.open(self.last_image_url)
        else:
            messagebox.showinfo("No URL", "Load an image first.")

    def clear_browser_cache(self) -> int:
        """Delete only files created by this browser, not arbitrary user files."""
        cache_dir = Path(self.cache_dir_var.get().strip().strip('"') or DEFAULT_CACHE_DIR)
        if not cache_dir.exists() or not cache_dir.is_dir():
            return 0
        patterns = [
            "probolism_*.jpg",
            "probolism_*.jpeg",
            "probolism_*.png",
            "probolism_*.json",
            "probolism_*.tmp",
            "probolism_*.jpg.tmp",
            "galaxy_name_resolutions.json",
        ]
        deleted = 0
        for pattern in patterns:
            for path in cache_dir.glob(pattern):
                try:
                    if path.is_file():
                        path.unlink()
                        deleted += 1
                    elif path.is_dir():
                        shutil.rmtree(path)
                        deleted += 1
                except Exception:
                    pass
        return deleted

    def on_close(self) -> None:
        self.bulk_stop_event.set()
        if self.clear_cache_on_exit_var.get():
            self.clear_browser_cache()
        self.root.destroy()

    def show_user_guide(self) -> None:
        guide = """Probolisms browser by piotrs — user guide

Purpose
-------
This program is a CSV browser for candidate probolisms. It does not calculate probolisms by itself. It works together with a separate probolism-calculation program, which searches star and galaxy catalogues and writes the results to CSV files. This browser opens one of those CSV files and shows an online sky image centered on each candidate field.

Opening data
------------
1. Click "Choose CSV…" and select one CSV file created by the calculation program.
2. The browser reads the file, shows the number of records, and displays the first record.
3. The record panel shows the field center, constellation, nearest galaxy to the field center, g_star, g_gal, P_raw, P_norm, class, and the galaxies listed in the CSV row.

Image source and cache
----------------------
The image is downloaded from CDS/Aladin HiPS2FITS using the selected HiPS survey. Each downloaded image is stored in the chosen cache folder. Returning to the same record with the same field and survey reads the image from cache instead of downloading it again.

The "Load all images to cache" button goes through all records in the loaded CSV file and prepares their images in the cache folder. The progress bar shows how many records have already been processed and how many errors occurred. This is useful before visual browsing, because later movement between records is faster and does not normally require another internet request. If the online service is temporarily slow, the browser repeats the download attempt before marking a record as an error.

While bulk loading is running, the "Stop loading images" button appears directly below "Load all images to cache". It stops the bulk cache loading after the current image operation finishes. Pressing "Load all images to cache" again resumes from the next not-yet-processed record in the currently loaded CSV list. Loading a new CSV file resets this position, so bulk loading starts from the beginning of the new list.

The "Refresh / download again" button reloads the currently displayed record and writes a fresh image to cache. The "Open image URL" button opens the current online image request in a web browser.

Field of view
-------------
The Selected field list contains square fields: 0.3x0.3, 0.5x0.5, 0.7x0.7, 1x1, 2x2, and 4x4 degrees. The displayed/downloaded image is always larger by 0.1° in each direction. For example, selecting 0.3x0.3 displays/downloads 0.4° × 0.4°. The exact displayed field is written below the image.

Browsing records
----------------
Right arrow or down arrow: next record.
Left arrow or up arrow: previous record.
Mouse wheel without Ctrl: next/previous record.
At the end of the list the program beeps briefly and wraps around to the beginning. The same happens in the opposite direction.

Moving and zooming the image
----------------------------
Ctrl + left mouse drag: move/pan the image.
Ctrl + mouse wheel: zoom in or out.
Use the "Reset image view" button to restore the original scale and position.

Selecting and exporting records
-------------------------------
Use the "Selected record" checkbox to select or unselect the current record. The "Selected" counter shows how many records are currently selected. Selected records remain selected when you move to another row in the CSV file.

Use "Export selected to JPG…" to save the selected records as JPG files. The browser asks for a base file name and then creates consecutive JPG files with suffixes such as _001, _002, _003. Each JPG normally contains up to two selected records arranged vertically. If a selected record contains more than five galaxies in its galaxy list, that record is saved alone in its own JPG file; in that one-record JPG the galaxy names are written in one comma-separated line instead of a vertical bullet list. Every item contains the sky image and the same kind of record parameters that are shown in the "Record parameters" panel.

At the same time, the browser also writes one common CSV file with all selected records. This CSV is saved in the same folder and with the same base name as the exported JPG files. For example, choosing selected.jpg creates selected_001.jpg, selected_002.jpg, and selected.csv. If an image is not already available in cache, the browser prepares it using the same CDS/Aladin HiPS2FITS image request mechanism.

Cache cleanup
-------------
If "Clear browser cache on exit" is checked, the program removes files created by this browser from the selected cache folder when the window is closed. It does not delete unrelated user files.

Optional automatic field enlargement
------------------------------------
The "Auto" option tries to resolve galaxy names from the CSV row through Astropy/Sesame. If resolved galaxies require a larger view, the field is enlarged. If name resolution fails, the browser keeps the normal selected field.

Authorship
----------
© 2026 piotrs. All rights reserved.
This program was developed by the author with the use of AI tools, including ChatGPT, as support in creating and improving the code.
"""
        win = tk.Toplevel(self.root)
        win.title("User guide")
        win.geometry("760x640")
        win.minsize(600, 420)
        frame = ttk.Frame(win, padding=8)
        frame.pack(fill="both", expand=True)
        text = tk.Text(frame, wrap="word")
        scroll = ttk.Scrollbar(frame, orient="vertical", command=text.yview)
        text.configure(yscrollcommand=scroll.set)
        text.grid(row=0, column=0, sticky="nsew")
        scroll.grid(row=0, column=1, sticky="ns")
        frame.rowconfigure(0, weight=1)
        frame.columnconfigure(0, weight=1)
        text.insert("1.0", guide)
        text.configure(state="disabled")
        ttk.Button(frame, text="Close", command=win.destroy).grid(row=1, column=0, columnspan=2, pady=(8, 0))


def main() -> None:
    root = tk.Tk()
    try:
        style = ttk.Style(root)
        if "vista" in style.theme_names():
            style.theme_use("vista")
    except Exception:
        pass
    ProbolismCsvBrowser(root)
    root.mainloop()


if __name__ == "__main__":
    main()
